import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const localApiJson = path.join(dir, "api.json")
// 不再从网络获取，只使用本地 api.json 作为唯一数据源
// const modelsData = fs.existsSync(localApiJson)
//   ? await Bun.file(localApiJson).text()
//   : await fetch(`${process.env.OPENCODE_MODELS_URL || "https://models.dev"}/api.json`).then((x) => x.text())
if (!fs.existsSync(localApiJson)) {
  throw new Error("api.json not found — this file is the single source of truth for model definitions")
}
const modelsData = await Bun.file(localApiJson).text()
// jk-j60099994-replace-with-api-1-start
// jk-j60099994-replace-with-api-1-end
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
